### ISSUE TITLE
Cant erase default "1" expense value

### ISSUE THREAD

**Issue by per-samuelsson** [warpech/HelloWorld#7] opened 2016-06-08 10:09 UTC
1. Clone and run.
2. Create a new expense.
3. Name it something and _click_ the expense value textbox. Without _highlighting_ the "1", try to erase it (with backspace). It won't let you.

Suggestion: allow me to do so, and treat that as 0.

**Comment by per-samuelsson** [comment] 2016-06-08 10:16
(Oh, it's fine if you decide we don't fix this. Just close it if so)

**Comment by warpech** [comment] 2016-06-24 14:33
I think this is a valid request. It seems to be Typed JSON issue. @chrhol can you take a look?

This is the view-model:

``` json
{
  "_ver#c$":0,
  "_ver#s":0,
  "Html":"/HelloWorld/PersonJson.html",
  "FirstName$":"John",
  "LastName$":"Doe",
  "Save$":0,
  "FullName":"John Doe",
  "Expenses":[
    {
      "HelloWorld":{
        "Html":"/HelloWorld/ExpenseJson.html",
        "Description$":"Milk",
        "Amount$":1
      }
    }
  ],
  "AddNewExpense$":0,
  "CurrentBalance":1,
  "Cancel$":0,
  "DeleteAll$":0
}
```

### Request

This is the outgoing patch from client:

``` json
[{"op":"replace","path":"/_ver#c$","value":1},
{"op":"test","path":"/_ver#s","value":1},
{"op":"replace","path":"/Expenses/0/HelloWorld/Amount$","value":""}]
```

### Actual response

This is the response from the server:

``` json
[{"op":"replace","path":"/_ver#s","value":2},
{"op":"test","path":"/_ver#c$","value":1},
{"op":"replace","path":"/Expenses/0/HelloWorld/Amount$","value":1}]
```

### Expected response

This would be the expected response from the server:

``` json
[{"op":"replace","path":"/_ver#s","value":2},
{"op":"test","path":"/_ver#c$","value":1},
{"op":"replace","path":"/Expenses/0/HelloWorld/Amount$","value":0}]
```

**Comment by chrhol** [comment] 2016-06-27 07:04
What happens is that parsing an empty string fails, it cannot be converted to an integer. And the current value is returned to client, since the request from the client to change the value was denied. Same as what happens if an inputhandler call `input.Cancel()`.

So empty strings should be treated as the default value for the specified type then?

**Comment by warpech** [comment] 2016-06-27 10:33
> So empty strings should be treated as the default value for the specified type then?

In JavaScript, empty string coerces to numeric `0`. Therefore, my gut feeling would be to treat an empty string as 0 (not the default value). But then again, JavaScript's type coercion is far from perfect, so I may be wrong.

On the other hand, treating empty string as the default value sounds like a nice sub-feature. Would that be not [surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), though?

Can the default value be dynamically changed for a Typed JSON template?

**Comment by chrhol** [comment] 2016-06-27 10:39
> Can the default value be dynamically changed for a Typed JSON template?

Yes, the default value for a template is taken from what is used in JSON-by-example, so in this case the default template value would be 1, `"Amount$":1`.

However, the default value for the type (i.e integer) would be 0 and in this case, if we should treat empty string as default value, this would make more sense I think.

**Comment by warpech** [comment] 2016-06-27 11:05
> However, the default value for the type (i.e integer) would be 0 and in this case, if we should treat empty string as default value, this would make more sense I think.

Seems right.

**Comment by chrhol** [comment] 2016-06-28 13:16
If we change this, it has the side-effect of actually leaving the input-field empty, and if you look in the viewmodel on the client, the value will be empty, but still treated as 0 on the server. Is this ok? 

The reason is that we have the optimization on the server, that if the value is not changed on the server, there is no need to send a patch back with it.

**Comment by warpech** [comment] 2016-06-28 15:05
I think that it would be less surprising if the server responded with the
actual value. I think than when the client replaces a number with an empty
string (`""`), the server should replace the value back to the correct type
(`0`)
28 cze 2016 3:16 PM "Christian Holmstrand" notifications@github.com
napisał(a):

If we change this, it has the side-effect of actually leaving the
input-field empty, and if you look in the viewmodel on the client, the
value will be empty, but still treated as 0 on the server. Is this ok?

The reason is that we have the optimization on the server, that if the
value is not changed on the server, there is no need to send a patch back
with it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/StarcounterSamples/HelloWorld/issues/7#issuecomment-229045410,
or mute the thread
https://github.com/notifications/unsubscribe/AAikv3HI_HZrdZF96l3cH5V1wPnNILkcks5qQR6wgaJpZM4IwzO3
.

**Comment by chrhol** [comment] 2016-06-29 07:06
> I think that it would be less surprising if the server responded with the
> actual value. I think than when the client replaces a number with an empty
> string (`""`), the server should replace the value back to the correct type
> (`0`)

I agree, as for the end-result. However this is kind of a problematic area, and I'm not sure I can find a good implementation for it without it being a hack for this specific occurence. After the value is parsed, the server has no knowledge about it, other than if it was a correct value or not (i.e. could not be parsed to the correct type).

I will have to investigate it.

**Comment by chrhol** [comment] 2016-06-29 11:38
Alright, I think I found a solution for it that works. I have pushed the changes to develop and pnext. Please try it @per-samuelsson, and close it if works as intended

**Comment by ErlendLandro** [comment] 2016-11-08 14:54
Works as intended, no problem deleting the 1

**Closed as completed by ErlendLandro** 2016-11-08 14:54 UTC
Labels: bug
